---
title: "Portfolio Assignment 3"
author: "Evan O'Keefe"
date: "4/07/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r DataProcessing, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)

df <- read_csv("data/processed_data.csv") %>% 
  mutate(startTime = endTime - msPlayed / 1000,
         diff = startTime - lag(endTime),
         date = as.Date(endTime))
```

```{r ConstructDataFrame, message=FALSE}
days <- df %>% 
  group_by(date) %>% 
  summarize(listen_time = sum(msPlayed / 60000),
            songs = n())
```

```{r UpdateDataFrame, message=FALSE, warning=FALSE}
test <- df %>% 
  group_by(date, artistName) %>% 
  summarise(count = n()) %>% 
  pivot_wider(names_from = artistName, values_from = count, values_fill = 0)

days$top_artist <- colnames(test)[apply(test,1,which.max)]
```

```{r ShinyFunctions, message=FALSE}
library(plotly)

tooltip_fun <- function(day, artist, songs, seconds){
  paste("Date:", format(day, "%a %h %d"), '\n',
        "Top Artist:", artist, '\n',
        "Songs Played:", songs, '\n',
        "Total Playtime:", round(seconds_to_period(seconds)))
}

line_fun <- function(df, df2, start, end){
  p <- df %>% 
    filter(date > start, date < end) %>% 
    ggplot(aes(x = date, y = listen_time)) +
      geom_point(aes(text = tooltip_fun(date,
                                        top_artist,
                                        songs,
                                        listen_time * 60))) +
      geom_line() +
      labs(
        x = "Date",
        y = "Listening Time (Minutes)"
      )
  ggplotly(p, tooltip = c("text"))
}
```


```{r ShinyApp, fig.height=20, message=FALSE}
library(shiny)
library(zoo)

ui <- fluidPage(
   titlePanel("My Spotify Listening Data"),
   dateRangeInput("dateRange",
                  "Date Range:",
                  start = min(days$date),
                  end = max(days$date)),
   plotlyOutput("lineplot"),
   p("Click a point to open the associated dataframe below."),
   dataTableOutput("click")
)

server <- function(input, output) {
  lineplot <- reactive({
    line_fun(days, df, input$dateRange[1], input$dateRange[2])
  })
  output$lineplot = renderPlotly(lineplot())
  output$click <- renderDataTable({
    d <- event_data("plotly_click")
    if (is.null(d)) "Hello" else{
      hover_date <- as.Date(pull(d, x))
      df %>% 
        filter(date == hover_date) %>% 
        select(startTime, trackName, artistName, msPlayed)
    }
  })
}

```

